
project:
  name: mongodb-taskcat-example
  parameters:
    KeyPairName : "teresa"
  regions:
    - cn-northwest-1
    - cn-north-1
tests:
  my-test:
    regions:
      - cn-northwest-1
    parameters:
      KeyPairName : "teresa-test"
      RemoteAccessCIDR: "0.0.0.0/0"
      AvailabilityZones: "cn-northwest-1a,cn-northwest-1b,cn-northwest-1c"
      NumberOfAZs: "2"
      MongoDBAdminPassword: "Aa112233"
    template: ./mongodb-master.template
